### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [VoodooPrograms/1000#1]
1. Przydałoby się wzucić biblioteki zewnętrzne (tornado, coś jeszcze?) do pliku `requirements.txt` (składnię Pan sobie znajdzie) — dzięki temu użytkownik będzie mógł je zainstalować przez `pip install -r requirements.txt`

2. Wyrucić `Game/__pycache__`

3. Rozumiem, że `index.html` też może leżeć wewnątrz `Templates`?

4. Drobiazg: w `main.py` wolałbym taką kolejność importów ([punkt 3.13](https://google.github.io/styleguide/pyguide.html)):
```python
import datetime
import json
import os

import tornado.ioloop
import tornado.web
import tornado.websocket

import Game
```

5. Przydałyby się docstringi do modułów, klas, metod i funkcji.

6. Zamiast `from random import shuffle`, `from json import JsonEncoder`, `from Game.MessageWriter import MessageWriter` itp. wolę `import random` itp. ([punkt 2.2](https://google.github.io/styleguide/pyguide.html)).

7. Gettery w stylu `Card.getRank()` są niepytoniczne. Używać po prostu `card.rank`

8. Za długie wiersze, jak np. 41 w `Game/Game.py` podzielić (nie korzystać z `\` na końcu wierszy, tylko z nawiasów). Ponadto `card["filename"]` itp. raczej tam nie zadziałają — czy nie chodziło o `card.filename` itp.?

9. W `Round.is_pot_finished()` lepiej porównywać z `Round.CONTRACTS[-1]` niż z 200.

10. W `Game/Server.py` importy z `main` są na szczęście zbędne (pylint by to znalazł). Gdyby jednak były potrzebne, prosiłbym o przerobienie struktury modułów, bo stałaby na głowie.

**Comment by MarcinCiura** [comment]
Projekt wygląda bardzo porządnie. Mam tylko kilka kosmetycznych uwag.

1. Wyrzucić `Game/__pycache__`

2. [Tutaj](https://github.com/VoodooPrograms/1000/blob/cb3dc97ac2efd949da1b84b726d32eafb963a0ca/Game/Card.py#L7) lepiej skorzystać z `os.path.join()`.

3. Gettery nadal uważam za zbędne.

4. [Ten wiersz](https://github.com/VoodooPrograms/1000/blob/cb3dc97ac2efd949da1b84b726d32eafb963a0ca/Game/Game.py#L41) przełamać w sensownym miejscu. Ponieważ nastąpi to wewnątrz nawiasów, nie dodawać brzydkiego i zakazanego `\`.

5. Przydałby się komentarz, objaśniający magię w `JsonEncoder`.

6. [Tutaj](https://github.com/VoodooPrograms/1000/blob/cb3dc97ac2efd949da1b84b726d32eafb963a0ca/Game/Player.py#L23) elegancko byłoby rzucić `NotImplementedError`.

7. [`range(100, 210, 10)`](https://github.com/VoodooPrograms/1000/blob/cb3dc97ac2efd949da1b84b726d32eafb963a0ca/Game/Round.py#L5)?

8. [`{}` zamiast `dict()`](https://github.com/VoodooPrograms/1000/blob/cb3dc97ac2efd949da1b84b726d32eafb963a0ca/Game/ScoreKeeper.py#L6).

9. Może `index.html` będzie się lepiej czuł wewnątrz `static/html`?

**Comment by VoodooPrograms** [comment]
Uwagi przyjęte. Projekt gotowy do oddania

**Comment by MarcinCiura** [comment]
LGTM. Gratuluję, jest Pan dwudziesty drugi. W wolnej chwili proszę na końcu testów dopisać dwa magiczne wiersze.

Dodatkowa prośba: jeśli nikt tego przed Panem nie zrobi, proszę ogłosić konsultacje w niedzielę o 20:30 i w poniedziałek o 12:00 pod standardowym linkiem. Dziękuję!
